Notifier Microservice
harvard-lts/dais-notifier pull request #1
Opened 2023-04-12 23:19 UTC by ives1227

**A microservice that reads messages from a queue and sends out an email*
* * *

**Ticket Link**: https://jira.huit.harvard.edu/browse/LTSEPADD-94 (Parent is https://jira.huit.harvard.edu/browse/LTSEPADD-93)

# How should this be tested?

Follow the instructions here: https://github.com/harvard-lts/dais-notifier/blob/LTSEPADD-93/README.md#testing

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? yes
- integration tests? yes

2023-04-14 02:40 UTC, awoods requested changes
Some minor comments.

2023-04-14 02:40 UTC, awoods commented on gunicorn.conf.py
> +            'handlers': ['console'],
Should this handler instead be: 'error_console'?

2023-04-14 02:40 UTC, awoods commented on tests/integration/mqutils.py
> +class ConnectionParams:
Is this class ever used?

2023-04-14 02:40 UTC, awoods commented on tests/unit/test_notifier.py
> +def test_send_email_with_no_recipiants():
Typo: 'recipiants'

2023-04-14 02:40 UTC, awoods commented on tests/unit/test_notifier.py
> +def test_send_email_with_one_recipiant():
Typo: 'recipiants'

2023-04-14 02:40 UTC, awoods commented on tests/unit/test_notifier.py
> +def test_send_email_with_two_recipiants():
Typo: 'recipiants'

2023-04-15 21:30 UTC, ives1227 commented on Dockerfile
> +FROM python:3.8-slim-buster
I updated it - an oversight

2023-04-15 21:33 UTC, ives1227 commented on tests/integration/mqutils.py
> +class ConnectionParams:
Yes, throughout the mqutils module.

2023-04-15 21:34 UTC, ives1227 commented on tests/unit/test_notifier.py
> +def test_send_email_with_two_recipiants():
fixed

2023-04-15 21:35 UTC, ives1227 commented on tests/unit/test_notifier.py
> +def test_send_email_with_one_recipiant():
fixed

2023-04-17 00:07 UTC, awoods requested changes

2023-04-17 00:07 UTC, awoods commented on gunicorn.conf.py
> +            'handlers': ['console'],
Did you see this comment?

2023-04-17 00:09 UTC, ives1227 commented
@awoods just fixed that typo.

2023-04-17 00:09 UTC, ives1227 commented on gunicorn.conf.py
> +            'handlers': ['console'],
Just fixed.

2023-04-17 01:21 UTC, awoods approved these changes

2023-04-17 01:22 UTC, merged